#pragma once

#define HAL_BOARD_NAME "86Duino"
#define HAL_CPU_CLASS HAL_CPU_CLASS_1000
#define HAL_OS_POSIX_IO 1
#define HAL_OS_SOCKETS 0
#define HAL_STORAGE_SIZE            16384
#define HAL_STORAGE_SIZE_AVAILABLE  HAL_STORAGE_SIZE
#define HAL_BOARD_LOG_DIRECTORY "logs"
//#define HAL_BOARD_TERRAIN_DIRECTORY "terrain"
#define HAL_PARAM_DEFAULTS_PATH nullptr
// SPI sensor set GY-91, mpu9250 + bmp280
#define HAL_INS_DEFAULT HAL_INS_MPU9250_SPI
#define HAL_INS_DEFAULT_ROTATION ROTATION_NONE
#define HAL_INS_MPU9250_NAME "mpu9250"
#define HAL_BARO_DEFAULT HAL_BARO_BMP280_SPI
#define HAL_BARO_BMP280_NAME    "bmp280"
// including AK8963 by spi and HMC5843 by i2c 
#define HAL_COMPASS_DEFAULT HAL_COMPASS_86DUINO
// I2C sensor set GY-86, mpu6050 + ms5611 + HMC5883
//#define HAL_INS_DEFAULT HAL_INS_MPU60XX_I2C
//#define HAL_INS_MPU60x0_I2C_BUS     0
//#define HAL_INS_MPU60x0_I2C_ADDR    0x68
//#define HAL_BARO_DEFAULT HAL_BARO_MS5611_I2C
//#define HAL_BARO_MS5611_I2C_BUS     0
//#define HAL_BARO_MS5611_I2C_ADDR    0x77
//#define HAL_COMPASS_DEFAULT HAL_COMPASS_HMC5843
//#define HAL_COMPASS_HMC5843_I2C_BUS 0
//#define HAL_COMPASS_HMC5843_I2C_ADDR 0x1E
// SITL sensor set
//#define HAL_INS_DEFAULT HAL_INS_HIL
//#define HAL_BARO_DEFAULT HAL_BARO_HIL
//#define HAL_COMPASS_DEFAULT HAL_COMPASS_HIL
#define HAL_GPIO_A_LED_PIN        13
#define HAL_GPIO_B_LED_PIN        12
#define HAL_GPIO_C_LED_PIN        11
#define HAL_GPIO_LED_ON           LOW
#define HAL_GPIO_LED_OFF          HIGH

